sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 9001
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: <your_new_placeholder>
    access-key-id: <your_new_placeholder>
    access-key-secret: <your_new_placeholder>
    bucket-name: <your_new_placeholder>